name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      DOTNET_NOLOGO: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore PopupGuard.sln

      - name: Build (Release)
        run: dotnet build PopupGuard.sln -c Release --no-restore

      - name: Publish framework-dependent (win-x64, FDD)
        run: >
          dotnet publish src/App/App.csproj -c Release -r win-x64 --self-contained false
          -o dist/win-x64-fdd

      - name: Build MSI (WiX v4)
        run: dotnet build installer/Installer.wixproj -c Release

      - name: Prepare artifacts
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path artifacts | Out-Null
          Copy-Item installer/bin/x64/Release/PopupGuard.msi artifacts/PopupGuard.msi -Force
          Get-FileHash -Algorithm SHA256 artifacts/PopupGuard.msi | Format-Table -AutoSize | Out-String | Set-Content artifacts/SHA256SUMS.txt
          Compress-Archive -Path dist/win-x64-fdd/* -DestinationPath artifacts/PopupGuard-win-x64-fdd.zip -Force
          Get-FileHash -Algorithm SHA256 artifacts/PopupGuard-win-x64-fdd.zip | Format-Table -AutoSize | Out-String | Add-Content artifacts/SHA256SUMS.txt

      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v4
        with:
          name: PopupGuard-artifacts
          path: artifacts/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            解决了无法安装问题。
            - 切换为框架依赖版安装包（FDD）
            - 修复 MSI 有效负载未嵌入导致的安装失败
          files: |
            artifacts/PopupGuard.msi
            artifacts/PopupGuard-win-x64-fdd.zip
            artifacts/SHA256SUMS.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


